language: node_js
node_js:
  - '0.10'
before_install:
  - make install
services:
  - mongodb
notifications:
  email:
    - gildas.garcia@gmail.com
after_success:
  # Install the Heroku gem
  - gem install heroku
  # Add the heroku git repository
  - git remote add heroku git@heroku.com:mysessions.git
  # Turn off warnings about SSH keys:
  - echo "Host heroku.com" >> ~/.ssh/config
  - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "   CheckHostIP no" >> ~/.ssh/config
  - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
  # Clear your current Heroku SSH keys:
  - heroku keys:clear
  # Add a new SSH key to Heroku
  - yes | heroku keys:add
  # Push to Heroku!
  - yes | git push heroku master
